[versions]
kotlin = "1.9.24"
agp = "8.3.2"
composeBom = "2024.10.00"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
